name: Template - Build Frontend

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
    secrets:
      DOCKER_USER:
        required: true
      DOCKER_PAT:
        required: true
#        TODO: Add secrets
#      AZURE_AD_CLIENT_ID:
#        required: true
#      AZURE_AD_CLIENT_SECRET:
#        required: true
#      AZURE_AD_TENANT_ID:
#        required: true
#      NEXT_PUBLIC_API:
#        required: true
#      NEXTAUTH_SECRET:
#        required: true
#      NEXTAUTH_URL:
#        required: true

defaults:
  run:
    shell: pwsh

permissions:
  id-token: write
  contents: read

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Load .env file
        uses: xom9ikk/dotenv@v2
        with:
          path: ./.github
          load-mode: strict

      - name: Get current date
        id: date
        run: |
          echo "date=$(Get-Date -Format yyyy-MM-ddThh:mm:ssZ -AsUtc)" >> $env:GITHUB_OUTPUT

      - name: Docker - Set up Buildx
        uses: docker/setup-buildx-action@v2.5.0
        with:
          platforms: linux/amd64,linux/arm64

# TODO: propagate Azure CLI and Deploy
#      - name: Azure CLI - Login
#        uses: azure/login@v1
#        with:
#          client-id: ${{ secrets.AZURE_CLIENT_ID }}
#          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#
#      - name: ACR - Login
#        run: |
#          az acr login --name ${{ env.ACR_LOGIN_SERVER }}
#
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Docker - Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ inputs.tag }}
          build-args: |
            NEXT_PUBLIC_API=${{ github.WEB_API_URL }}
#            AZURE_AD_CLIENT_ID=${{ secrets.AZURE_AD_CLIENT_ID }}
#            AZURE_AD_CLIENT_SECRET=${{ secrets.AZURE_AD_CLIENT_SECRET }}
#            AZURE_AD_TENANT_ID=${{ secrets.AZURE_AD_TENANT_ID }}
#            NEXT_PUBLIC_API=${{ secrets.NEXT_PUBLIC_API }}
#            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
#            NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
